In [3]:
import pandas as pd
grades={ 'Sakshi':[99,100,99],
         'Arghya':[99,99,100],
         'Jasstin':[99,100,99],
         'Smruti':[99,100,99]
        }
g=pd.DataFrame(grades)
print(g)

   Sakshi  Arghya  Jasstin  Smruti
0      99      99       99      99
1     100      99      100     100
2      99     100       99      99

In [4]:
g['Smruti'][1]=99
print(g)

   Sakshi  Arghya  Jasstin  Smruti
0      99      99       99      99
1     100      99      100      99
2      99     100       99      99

In [7]:
g.index=['Test1','Test2','Test3']
g
print(g['Sakshi'])
print(g.Arghya)

Test1     99
Test2    100
Test3     99
Name: Sakshi, dtype: int64
Test1     99
Test2     99
Test3    100
Name: Arghya, dtype: int64

In [12]:
g.loc['Test1']

Sakshi     99
Arghya     99
Jasstin    99
Smruti     99
Name: Test1, dtype: int64

In [10]:
g.iloc[1]

Sakshi     100
Arghya      99
Jasstin    100
Smruti      99
Name: Test2, dtype: int64

In [14]:
g.loc['Test1':'Test3']

       Sakshi  Arghya  Jasstin  Smruti
Test1      99      99       99      99
Test2     100      99      100      99
Test3      99     100       99      99

In [15]:
g.iloc[0:2]

       Sakshi  Arghya  Jasstin  Smruti
Test1      99      99       99      99
Test2     100      99      100      99

In [16]:
g.loc[['Test1','Test3']]

       Sakshi  Arghya  Jasstin  Smruti
Test1      99      99       99      99
Test3      99     100       99      99

In [17]:
g.iloc[[0,2]]

       Sakshi  Arghya  Jasstin  Smruti
Test1      99      99       99      99
Test3      99     100       99      99

In [24]:
g[g>=90]

       Sakshi  Arghya  Jasstin  Smruti
Test1      99      99       99    99.0
Test2     100      99      100     NaN
Test3      99     100       99    99.0

In [22]:
g[(g>=80)&(g<90)]

       Sakshi  Arghya  Jasstin  Smruti
Test1     NaN     NaN      NaN     NaN
Test2     NaN     NaN      NaN    89.0
Test3     NaN     NaN      NaN     NaN

In [21]:
g['Smruti'][1]=89

In [27]:
g.at['Test2','Sakshi']

100

In [28]:
g.iat[2,0]

99

In [29]:
g.iat[1,2]=87
print(g)

       Sakshi  Arghya  Jasstin  Smruti
Test1      99      99       99      99
Test2     100      99       87      89
Test3      99     100       99      99

In [30]:
g.describe()

           Sakshi      Arghya    Jasstin     Smruti
count    3.000000    3.000000   3.000000   3.000000
mean    99.333333   99.333333  95.000000  95.666667
std      0.577350    0.577350   6.928203   5.773503
min     99.000000   99.000000  87.000000  89.000000
25%     99.000000   99.000000  93.000000  94.000000
50%     99.000000   99.000000  99.000000  99.000000
75%     99.500000   99.500000  99.000000  99.000000
max    100.000000  100.000000  99.000000  99.000000

In [32]:
g.mean()

Sakshi     99.333333
Arghya     99.333333
Jasstin    95.000000
Smruti     95.666667
dtype: float64

In [33]:
g.T.mean()

Test1    99.00
Test2    93.75
Test3    99.25
dtype: float64

In [34]:
g.sort_index(ascending=False)

       Sakshi  Arghya  Jasstin  Smruti
Test3      99     100       99      99
Test2     100      99       87      89
Test1      99      99       99      99

In [35]:
g.sort_index(axis=1)

       Arghya  Jasstin  Sakshi  Smruti
Test1      99       99      99      99
Test2      99       87     100      89
Test3     100       99      99      99

In [36]:
g.sort_values(by='Test1',axis=1,ascending=False)

       Sakshi  Arghya  Jasstin  Smruti
Test1      99      99       99      99
Test2     100      99       87      89
Test3      99     100       99      99

In [37]:
g.loc['Test1'].sort_values(ascending=False)

Sakshi     99
Arghya     99
Jasstin    99
Smruti     99
Name: Test1, dtype: int64

In [44]:
g['Sakshi'][0]=100
g

       Sakshi  Arghya  Jasstin  Smruti
Test1     100      99       99      99
Test2     100      99       87      89
Test3      99     100       99      99

In [45]:
g.loc['Test1'].sort_values(ascending=False)

Sakshi     100
Arghya      99
Jasstin     99
Smruti      99
Name: Test1, dtype: int64

In [48]:
#Inplace Sorting
g.sort_index(ascending=False,inplace=True)
g

       Sakshi  Arghya  Jasstin  Smruti
Test3      99     100       99      99
Test2     100      99       87      89
Test1     100      99       99      99